apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: entportal-$service_name
spec:
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
    resources:
      limits:
        cpu: 800m
        memory: 1500Mi
      requests:
        cpu: 800m
        memory: 1500Mi
  template:
    metadata:
      labels:
        app: entportal-$service_name
    spec:
      imagePullSecrets:
        - name: artifactory-secret
      containers:
        - name: entportal-$service_name
          image: enterpriseprotal-docker-dev-local.artifactory.dhl.com/enterpriseprotal-docker-uat/entportal-$service_name:$image_tag
          ports:
          - containerPort: 7053
            protocol: TCP
          resources:
            limits:
              cpu: "800m"
              memory: "1500Mi"
            requests:
              cpu: "800m"
              memory: "1500Mi"
          livenessProbe:
            httpGet: 
              path: /entportal-$service_name
              port: 7053
            initialDelaySeconds: 15  
            periodSeconds: 10        
          readinessProbe:
            httpGet:
              path: /entportal-$service_name
              port: 7053
            initialDelaySeconds: 5
            periodSeconds: 5